#!/bin/sh
alias zsh-update-plugins="find "~/zsh/plugins" -type d -exec test -e '{}/.git' ';' -print0 | xargs -I {} -0 git -C {} pull -q"
# alias nvimrc='nvim ~/.config/nvim/'

# get fastest mirrors
# Colorize grep output (good for log files)
alias grep='grep --color=auto'

alias szsh="source $HOME/.zshrc"
alias vim="nvim"
alias mas="cd ~/Desktop/Master/"
alias k="kubectl"
if [ "$TERM" = "xterm-kitty" ]; then
  alias ssh="kitty +kitten ssh"
fi
alias icat="kitty +kitten icat"

case "$(uname -s)" in

   Darwin)
     # echo 'Mac OS X'
	alias ls='ls -G'
     ;;

   Linux)
	alias ls='ls --color=auto'
     ;;

   CYGWIN*|MINGW32*|MSYS*|MINGW*)
     # echo 'MS Windows'
     ;;
   *)
     # echo 'Other OS' 
     ;;
esac
