#!/bin/sh
HISTFILE="$XDG_DATA_HOME"/zsh/history
HISTSIZE=1000000
SAVEHIST=1000000

export PATH="$HOME/.emacs.d/bin:$PATH"
# For HomeBrew
export PATH="/usr/local/sbin:$PATH"
export PATH="$HOME/anaconda3/bin:$PATH"
#export PKG_CONFIG_PATH="/usr/local/lib/pkgconfig:/usr/local/Cellar/libpng/1.6.37/lib/pkgconfig:/opt/X11/lib/pkgconfig:/usr/local/Cellar/zlib/1.2.11/lib/pkgconfig:/usr/local/Cellar/libffi/3.3_3/lib/pkgconfig:/usr/local/Cellar/poppler/21.07.0/lib/pkgconfig:$PKG_CONFIG_PATH"
export EDITOR=nvim
export PAGER=nvimpager
