#!/bin/sh
alias zsh-update-plugins="find "~/zsh/plugins" -type d -exec test -e '{}/.git' ';' -print0 | xargs -I {} -0 git -C {} pull -q"
# alias nvimrc='nvim ~/.config/nvim/'

# get fastest mirrors
# Colorize grep output (good for log files)
alias grep='grep --color=auto'

alias szsh="source $HOME/.zshrc"
alias vim="nvim"
alias mas="cd ~/Desktop/Master/"
alias k="kubectl"
if [ "$TERM" = "xterm-kitty" ]; then
  alias ssh="kitty +kitten ssh"
fi
alias icat="kitty +kitten icat"
alias lg="lazygit"
# general use

if (( $+commands[exa])); then
  alias ls='exa -1 --icons'
  alias lsa='exa -1a --icons'
  alias l='exa -lb --icons'
  alias la='exa -lba --icons'
  alias lt='exa --icons --tree --level=2'
  alias lta='exa -a --icons --tree --level=2'
else
  case "$(uname -s)" in

     Darwin)
       # echo 'Mac OS X'
      alias ls='ls -1 -G'
      alias lsa='ls -1a -G'
      alias l='ls -lb -G'
      alias la='ls -lba -G'
      alias lt='tree -L 2'
      alias lta='tree -La 2'
       ;;

     Linux)
      alias ls='ls -1 --color=auto'
      alias lsa='ls -1a --color=auto'
      alias l='ls -lb --color=auto'
      alias la='ls -lba --color=auto'
      alias lt='tree -L 2'
      alias lta='tree -La 2'
       ;;

     CYGWIN*|MINGW32*|MSYS*|MINGW*)
       # echo 'MS Windows'
       ;;
     *)
       # echo 'Other OS' 
       ;;
  esac
fi
