#!/bin/sh
alias zsh-update-plugins="find "~/zsh/plugins" -type d -exec test -e '{}/.git' ';' -print0 | xargs -I {} -0 git -C {} pull -q"
# alias nvimrc='nvim ~/.config/nvim/'

# get fastest mirrors
# Colorize grep output (good for log files)
alias grep='grep --color=auto'

alias szsh="source $HOME/.zshrc"
alias vim="nvim"
alias mas="cd ~/Desktop/Master/"
alias k="kubectl"
if [ "$TERM" = "xterm-kitty" ]; then
  alias ssh="kitty +kitten ssh"
fi
alias icat="kitty +kitten icat"

# general use
alias ls='exa'  # ls
alias lsa='exa'  # ls
alias l='exa -lbF --git' # list, size, type, git
alias ll='exa -lbGF --git' # long list
alias llm='exa -lbGd --git --sort=modified' # long list, modified date sort
alias la='exa -lbhHigUmuSa --time-style=long-iso --git --color-scale'  # all list
alias lx='exa -lbhHigUmuSa@ --time-style=long-iso --git --color-scale' # all + extended list

# specialty views
alias lS='exa -1'   # one column, just names
alias lSa='exa -1 --all'   # one column, just names
alias lt='exa --tree --level=2'                                       

# case "$(uname -s)" in

#    Darwin)
#      # echo 'Mac OS X'
# 	alias ls='ls -G'
#      ;;

#    Linux)
# 	alias ls='ls --color=auto'
#      ;;

#    CYGWIN*|MINGW32*|MSYS*|MINGW*)
#      # echo 'MS Windows'
#      ;;
#    *)
#      # echo 'Other OS' 
#      ;;
# esac
