#!/bin/sh
# Colorize grep output (good for log files)
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'

# confirm before overwriting something
alias cp="cp -i"
alias mv='mv -i'
alias rm='rm -i'

alias vim="nvim"

case "$(uname -s)" in

   Darwin)
     # echo 'Mac OS X'
	alias ls='ls -G'
     ;;

   Linux)
	alias ls='ls --color=auto'
     ;;

   CYGWIN*|MINGW32*|MSYS*|MINGW*)
     # echo 'MS Windows'
     ;;
   *)
     # echo 'Other OS' 
     ;;
esac
