#+TITLE: Doom Emacs Config
#+AUTHOR: Karl Wang

* Basic
** Personal Information
Setting name and email address
#+begin_src emacs-lisp
;; Some functionality uses this to identify you, e.g. GPG configuration, email
;; clients, file templates and snippets.
(setq user-full-name "Karl Wang"
      user-mail-address "kwkarlwang@gmail.com")
#+end_src

** Font
Setting font family
#+begin_src emacs-lisp
(setq doom-font (font-spec :family "Fira Code Light"
                           :size 13
                           ))
#+end_src

Disable all bold font
#+begin_src emacs-lisp
(after! doom-themes
  ;; (set-face-attribute 'bold nil :weight 'light)
  ;; (mapc
  ;;  (lambda (face)
  ;;    (when (eq (face-attribute face :weight) 'bold)
  ;;      (set-face-attribute face nil :weight 'normal)))
  ;;  (face-list))
  (setq doom-themes-enable-bold nil)
  )
#+end_src

Disable bold numbers
#+begin_src emacs-lisp
;; (after! highlight-numbers
;;   (set-face-bold 'highlight-numbers-number nil)
;;   )
#+end_src

** Theme
Dracula is my personal favorite
#+begin_src emacs-lisp
(setq doom-theme 'dracula)
;; (setq doom-dracula-brighter-comments t)
#+end_src

Change comment color and line number color for the TUI
#+begin_src emacs-lisp
(unless (display-graphic-p)
    (set-face-foreground 'font-lock-comment-face "#a8a8a8")
    (set-face-foreground 'line-number "#a8a8a8")
    (set-face-foreground 'font-lock-doc-face "#c6c6c6")
  ;;   (set-face-background 'default "undefined")

  (set-face-background 'region "#524867")
  (after! lsp-mode
    (set-face-background 'lsp-face-highlight-read "#acebfb")
    (set-face-background 'lsp-face-highlight-textual "#acebfb")
    (set-face-background 'lsp-face-highlight-write "#acebfb")
    (set-face-background 'markdown-code-face "#1c1c1c")
    )
  (after! magit
    (set-face-background 'magit-diff-removed-highlight "undefined")
    (set-face-background 'magit-diff-added-highlight "undefined")
    (set-face-background 'magit-diff-removed "undefined")
    (set-face-background 'magit-diff-added "undefined")
    )
  )
#+end_src
** Line
Use relative line number
#+begin_src emacs-lisp
(setq display-line-numbers-type 'relative)
#+end_src

** Keybindings
Toggle settings
#+begin_src emacs-lisp
(map!
 :leader
 :desc "Toggle Comment" "c SPC" (lambda ()(interactive)(evilnc-comment-or-uncomment-lines -1))
 :desc "Toggle Terminal" "j" (lambda ()(interactive)(+popup/toggle))
 :desc "Toggle line highlight" "t h" #'global-hl-line-mode
 )
#+end_src

** Better Defaults
No confirmation about quitting
#+begin_src emacs-lisp
(setq confirm-kill-emacs nil)
#+end_src

Set column line indicator
#+begin_src emacs-lisp
(setq-default fill-column 100)
#+end_src

Make line wrap around
#+begin_src emacs-lisp
(global-visual-line-mode)
#+end_src

Make document automatically refresh
#+begin_src emacs-lisp
(global-visual-line-mode)
#+end_src

Disable the bottom documentation popup
#+begin_src emacs-lisp
(global-eldoc-mode -1)
#+end_src

Treat "_" as part of the word
#+begin_src emacs-lisp
(modify-syntax-entry ?_ "w")
#+end_src

Better undo
#+begin_src emacs-lisp
(setq undo-limit 80000000
      evil-want-fine-undo t)
#+end_src

Split windows to the right and below
#+begin_src emacs-lisp
(setq evil-vsplit-window-right t
      evil-split-window-below t)
#+end_src

No new line comment with "o"
#+begin_src emacs-lisp
(setq +evil-want-o/O-to-continue-comments nil)
#+end_src

Make S work like before in vim
#+begin_src emacs-lisp
(remove-hook 'doom-first-input-hook #'evil-snipe-mode)
#+end_src

Disable spell checking by default
#+begin_src emacs-lisp
(remove-hook 'text-mode-hook #'spell-fu-mode)
#+end_src

Other defaults
#+begin_src emacs-lisp
(setq-default delete-by-moving-to-trash t
              window-combination-resize t)
#+end_src

* Auto Completion
** Company
Setting company, the completion engine
#+begin_src emacs-lisp
(after! company
  ;; Shortened keyboard typing auto complete delay
  (setq company-minimum-prefix-length 2
        company-idle-delay 0.0)
  ;; (add-to-list 'company--disabled-backends 'company-ispell)
  (set-company-backend! '(text-mode)
    '(:separate company-yasnippet company-files company-dabbrev))
  )
#+end_src

** LSP
Setting LSP
#+begin_src emacs-lisp
(after! lsp-mode
  (setq
   lsp-headerline-breadcrumb-enable nil  ; not useful
   lsp-signature-render-documentation nil ; really annoying
   lsp-signature-auto-activate nil ; really annoying
   lsp-log-io nil ; increases performance
   lsp-idle-delay 0.5
   )

  )
(after! lsp-ui
  (lsp-ui-sideline-mode -1) ; flycheck is better
  (setq
   lsp-ui-sideline-enable nil
   lsp-ui-doc-enable nil
   lsp-ui-doc-max-width 150
   lsp-ui-doc-max-height 30
   )

  ;; show documentation
  (map!
   :map lsp-ui-mode
   :leader
   :desc "Show Documentation" "k" #'lsp-ui-doc-show
   )
  )
#+end_src

*** TODO Python
Setting lsp settings for pyright
#+begin_src emacs-lisp
(after! lsp-pyright
  (setq lsp-pyright-python-executable-cmd "python3"
        lsp-pyright-multi-root nil
        lsp-pyright-use-library-code-for-types t
        lsp-pyright-diagnostic-mode "workspace"
        )
  ;; (lsp-register-client
  ;;   (make-lsp-client
  ;;     :new-connection (lsp-tramp-connection (lambda ()
  ;;                                     (cons "pyright-langserver"
  ;;                                           lsp-pyright-langserver-command-args)))
  ;;     :major-modes '(python-mode)
  ;;     :remote? t
  ;;     :server-id 'pyright-remote
  ;;     :multi-root t
  ;;     :priority 3
  ;;     :initialization-options (lambda () (ht-merge (lsp-configuration-section "pyright")
  ;;                                                  (lsp-configuration-section "python")))
  ;;     :initialized-fn (lambda (workspace)
  ;;                       (with-lsp-workspace workspace
  ;;                         (lsp--set-configuration
  ;;                         (ht-merge (lsp-configuration-section "pyright")
  ;;                                   (lsp-configuration-section "python")))))
  ;;     :download-server-fn (lambda (_client callback error-callback _update?)
  ;;                           (lsp-package-ensure 'pyright callback error-callback))
  ;;     :notification-handlers (lsp-ht ("pyright/beginProgress" 'lsp-pyright--begin-progress-callback)
  ;;                                   ("pyright/reportProgress" 'lsp-pyright--report-progress-callback)
  ;;                                   ("pyright/endProgress" 'lsp-pyright--end-progress-callback))))
  )
#+end_src

*** Latex
Disable SPC as a trigger key and annoying eldoc
#+begin_src emacs-lisp
(add-hook! 'lsp-texlab-after-open-hook (eldoc-mode -1)
           (lsp:set-completion-options-trigger-characters?
            (lsp:server-capabilities-completion-provider?
             (lsp--workspace-server-capabilities (cl-first
                                                  (lsp-workspaces)
                                                  )))
            ["\\" "{" "}" "@" "/"])
           )

#+end_src

*** Docker
Disable SPC as a trigger key
#+begin_src emacs-lisp
(add-hook! 'lsp-dockerfile-ls-after-open-hook
           (lsp:set-completion-options-trigger-characters?
            (lsp:server-capabilities-completion-provider?
             (lsp--workspace-server-capabilities (cl-first
                                                  (lsp-workspaces)
                                                  )))
            ["=" "$" "-"])
           )
#+end_src

* Programming
** Markdown
Create a export shortcut for markdown
#+begin_src emacs-lisp
(defun markdown-export-pdf ()
  "Export the current markdown to pdf using pandoc"
  (interactive)
  (save-buffer)
  (shell-command (concat "pandoc "
                         buffer-file-name
                         " -V geometry:margin=1in --pdf-engine=pdflatex -o "
                         (file-name-sans-extension buffer-file-name)
                         ".pdf"))
  )
(map!
 :map markdown-mode-map
 :localleader
 :desc "Export" "m" #'markdown-export-pdf)
#+end_src

** Python
General python settings and keybindings
#+begin_src emacs-lisp
(after! python
  ;; set shell
  (setq python-shell-interpreter "python3"
        ;; python-shell-interpreter-args "--simple-prompt"
        python-shell-prompt-detect-failure-warning nil)
  (add-to-list 'python-shell-completion-native-disabled-interpreters "python3")

  ;; NOTE: reenable lsp after format, local hook
  (add-hook 'python-mode-hook (lambda() (add-hook 'after-save-hook #'lsp nil t)))

  ;; keybindings
  (map!
   :map python-mode-map
   :n "<" #'python-indent-shift-left
   :n ">" #'python-indent-shift-right
   (:localleader
    :desc "New cell" "s" (lambda() (interactive) (insert "\n# %%\n"))
    :desc "New cell below" "S" (lambda() (interactive)
                                 (insert "\n# %%\n")
                                 (previous-line)
                                 (previous-line))
    )
   )
  )
#+end_src
*** Jupyter
Jupyter is used for interactive shell, similar to VSCode
#+begin_src emacs-lisp
(use-package! jupyter
  :init
  ;; print to the REPL buffer
  (setq jupyter-repl-echo-eval-p t
        jupyter-repl-allow-RET-when-busy t
        )

  (defun init-jupyter-repl()
    "Initialize a python jupyter repl"
    (interactive)
    (set-face-background 'jupyter-repl-traceback nil)
    (jupyter-repl-associate-buffer
     (jupyter-run-repl "python37464bitbasecondabf9c15066bab4a48b97e94b7e7c780cc"))
    (jupyter-repl-pop-to-buffer)
    (previous-window-any-frame)
    )

  ;; set python jupyter shortcut
  (map!
   :map python-mode-map
   (:localleader
    (:prefix-map ("j" . "jupyter")
     :desc "Open REPL" "j"  #'init-jupyter-repl
     :desc "Show buffer" "s" (lambda()(interactive)
                               (jupyter-repl-pop-to-buffer)
                               (previous-window-any-frame))
     :desc "Associate buffer" "a" (lambda() (interactive) (jupyter-repl-associate-buffer))
     ))
   :ni "C-n" #'code-cells-forward-cell
   :ni "C-p" #'code-cells-backward-cell
   )
  )
#+end_src

*** Numpy Doc
Numpy Doc helps generate documentation for the python code
#+begin_src emacs-lisp
(use-package! numpydoc
  :after python
  :init
  (setq numpydoc-insertion-style nil)
  (map!
   :map python-mode-map
   :localleader
   :desc "Docstring" "d" #'numpydoc-generate
   ))
#+end_src

*** Code Cells
Code cells recognize "# %%" as a cell, used with jupyter
#+begin_src emacs-lisp
(use-package! code-cells
  :hook ((python-mode . code-cells-mode))
  :after python
  :init
  ;; map forcut
  (map!
   :map python-mode-map
   :ni "C-<return>" (lambda()(interactive) (code-cells-do
                                            (pulse-momentary-highlight-region start end)
                                            (jupyter-eval-region start end)))

   :ni "S-<return>" (lambda()(interactive) (code-cells-do
                                            (pulse-momentary-highlight-region start end)
                                            (jupyter-eval-region start end)
                                            (code-cells-forward-cell)
                                            ))
   ;; used for general repl
   (:localleader
    :desc "Run cell python" "m" (code-cells-command 'python-shell-send-region)
    ))
  )
#+end_src

** Org
Org settings. Make sure the latex preview is high definition SVG
#+begin_src emacs-lisp
(after! org
  ;;adjust the scale of latex preview
  (plist-put org-format-latex-options :scale 1.1)
  (setq org-preview-latex-default-process 'dvisvgm)
  (map!
   :map org-mode-map
   :localleader
   :desc "Latex preview" "m" #'org-latex-preview))
#+end_src

** Latex
Setting latex. Make <return> as latex preview
#+begin_src emacs-lisp
(after! tex
  (setq TeX-parse-self t
        TeX-auto-save t
        LaTeX-indent-level 4
        )
  (map!
   :map LaTeX-mode-map
   :n "RET" #'org-latex-preview
   :localleader
   :desc "View" "v" #'TeX-view
   )
  )
#+end_src

* Utility
** Format
Minimized the popup factor of format error
#+begin_src emacs-lisp
(set-popup-rule! "^\\*format-all" :size 0.01 :ttl 0 :modeline nil)
#+end_src

Use yapf formatting for python
#+begin_src emacs-lisp
(after! format-all
  (set-formatter! 'yapf "yapf -q " :modes'(python-mode))
  )
#+end_src
** Tree Sitter
Tree sitter is used to give semantic highlighting to code.
#+begin_src emacs-lisp
(use-package! tree-sitter
  :init
  (defun toggle-tree-sitter ()
    (interactive)
    (if tree-sitter-mode
        (tree-sitter-mode -1)
      (tree-sitter-hl-mode))
    )
  (map!
   :leader
   :desc "Toggle tree-sitter" "t t" #'toggle-tree-sitter
   )
  :config
  (require 'tree-sitter-langs)
  ;; Treat jupyter and python shell as python
  (pushnew! tree-sitter-major-mode-language-alist '(jupyter-repl-mode . python))
  (pushnew! tree-sitter-major-mode-language-alist '(inferior-python-mode . python))
  :hook (
         ;; enable tree sitter for the following mode
         (python-mode . tree-sitter-hl-mode)
         (jupyter-repl-mode . tree-sitter-hl-mode)
         (inferior-python-mode . tree-sitter-hl-mode)

         ;; make method call and function call the same color as function name
         ;; (prog-mode . (lambda ()
         ;;                  (add-function :before-until (local 'tree-sitter-hl-face-mapping-function)
         ;;                                (lambda (capture-name)
         ;;                                  (pcase capture-name
         ;;                                    ;; ("method.call" 'font-lock-function-name-face)
         ;;                                    ;; ("function.call" 'font-lock-function-name-face)
         ;;                                    ;; ("variable.parameter" 'default)
         ;;                                    ;; ("constant" 'default)
         ;;                                    )))))
         )
  )
#+end_src
** PDF tools
The emacs pdf viewer. Enabled dark mode by default and use continuous scroll package.
#+begin_src emacs-lisp
(use-package pdf-view
  :hook (pdf-tools-enabled . pdf-view-midnight-minor-mode)
  :hook (pdf-tools-enabled . hide-mode-line-mode)
  :hook (pdf-tools-enabled . pdf-continuous-scroll-mode)
  :config
  (map!
   :map pdf-continuous-scroll-mode-map
   :n "j" #'pdf-continuous-scroll-forward
   :n "k" #'pdf-continuous-scroll-backward
   :n "g g" #'pdf-cscroll-first-page
   :n "G" #'pdf-cscroll-last-page
   :n "l" #'pdf-cscroll-image-forward-hscroll
   :n "h" #'pdf-cscroll-image-backward-hscroll
   :n "C-d" #'pdf-view-scroll-down-or-previous-page
   :n "C-u" #'pdf-view-scroll-up-or-next-page
   )
  (map!
   :map pdf-view-mode-map
   :n "c" #'pdf-continuous-scroll-mode
   )
  )
#+end_src
** Spell check
Make sure the set dictionary. Otherwise, personal dictionary would not work.
#+begin_src emacs-lisp
(after! ispell
  (setq ispell-dictionary "en")
  )
#+end_src
** Rainbow mode
Rainbow mode turns on the colored parentheses
#+begin_src emacs-lisp
(add-hook! '(prog-mode-hook) #'rainbow-mode #'rainbow-delimiters-mode
           )
#+end_src
** TODO Tramp
#+begin_src emacs-lisp
;; (setq enable-remote-dir-locals t)
;; (setq enable-local-variables :all)
;; (after! tramp
;;   (add-to-list 'tramp-remote-path 'tramp-own-remote-path))
#+end_src

** Magit
Disable long summary warning
#+begin_src emacs-lisp
(after! magit
  (setq git-commit-style-convention-checks nil)
  )
#+end_src
