format = """
$username\
$hostname\
$shlvl\
$directory\
$vcsh\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$hg_branch\
$package\
$dotnet\
$nim\
$red\
$memory_usage\
$env_var\
$custom\
$cmd_duration\
$time\
$line_break\
$jobs\
$battery\
$status\
$shell\
$character"""
[aws]
disabled = true

[nodejs]
disabled = true

[python]
disabled = true

[package]
disabled = true

[rust]
disabled = true

[ruby]
disabled = true

[lua]
disabled = true

[java]
disabled = true

[time]
disabled = false

