apiVersion: v1
kind: Pod
metadata:
  name: karl
spec:
  # affinity:
  #   nodeAffinity:
  #     requiredDuringSchedulingIgnoredDuringExecution:
  #       nodeSelectorTerms:
  #         - matchExpressions:
  #           - key: gpu-type
  #             operator: In
  #             values:
  #             - 2080Ti
  containers:
  - name: gpu-container
    image: gitlab-registry.nautilus.optiputer.net/jiacheng/docker-images:torch17v4_jiacheng
    args: ["sleep", "infinity"]
    volumeMounts:
    - mountPath: /data
      name: data
    - mountPath: /dev/shm
      name: dshm
    resources:
      limits:
        memory: 8Gi
        nvidia.com/gpu: "1"
        cpu: "2"
      requests:
        memory: 8Gi
        nvidia.com/gpu: "1"
        cpu: "2"
  restartPolicy: Never
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: storage
    - name: dshm
      emptyDir:
        medium: Memory
        
