apiVersion: batch/v1
kind: Job
metadata:
  name: karl-job-0.6
spec:
  template:
    spec:
      #affinity:
        #nodeAffinity:
          #requiredDuringSchedulingIgnoredDuringExecution:
            #nodeSelectorTerms:
              #- matchExpressions:
                  #- key: gpu-type
                    #operator: In
                    #values:
                    #- "2080"

      containers:
        - name: gpu-container
          image: gitlab-registry.nautilus.optiputer.net/jiacheng/docker-images:torch17v4_jiacheng
          command:
            - bash
            - -c
            - "nvidia-smi && source /data/karl/setup.sh && cd /data/karl/srip-adabins && git pull origin seg_siyuan_karl && python train.py args_train_nyu_0.6.txt"

          volumeMounts:
            - mountPath: /data
              name: data
            - mountPath: /dev/shm
              name: dshm
          resources:
            limits:
              memory: 16Gi
              nvidia.com/gpu: "6"
              cpu: "8"
            requests:
              memory: 16Gi
              nvidia.com/gpu: "6"
              cpu: "8"
      restartPolicy: Never
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: storage
        - name: dshm
          emptyDir:
            medium: Memory
  backoffLimit: 1
