# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.
"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

# preset keymap
# https://github.com/sxyazi/yazi/blob/main/yazi-config/preset/keymap.toml

[[input.prepend_keymap]]
on = ["<Esc>"]
run = "close"
desc = "Cancel input"

[[manager.prepend_keymap]]
on = ["q"]
run = "quit --no-cwd-file"
desc = "Exit the process without writing cwd-file"

[[manager.prepend_keymap]]
on = ["Q"]
run = "quit"
desc = "Exit the process"
