# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.
"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

# preset config
# https://github.com/sxyazi/yazi/blob/main/yazi-config/preset/yazi.toml

[manager]
show_hidden = true

[preview]
max_width = 1200
max_height = 1800
